# -*- coding: utf-8 -*-
"""backtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wMTF6aXr_vXm9FwQ6LFjfCWk3Z4__ELx
"""

# src/backtest.py

import numpy as np
import pandas as pd
from sklearn.base import clone
from sklearn.metrics import mean_absolute_error
from src.metrics import pnl_loss
from tqdm import tqdm
import time


def expanding_window_backtest(
    model,
    X,
    y,
    dates,
    train_window_days=500,
    retrain_freq=1,
    lookback_days=None,
    verbose=True
):
    """
    Walk-forward бэктест с переобучением модели.

    Параметры:
    ----------
    model : sklearn-совместимая модель
    X : pd.DataFrame
        Признаки (индекс должен совпадать с y и dates)
    y : pd.Series
        Целевая переменная
    dates : pd.Series или array
        Даты (для временной разбивки)
    train_window_days : int
        Минимальный размер обучающей выборки в днях (≈2 года = 500)
    retrain_freq : int
        Частота переобучения (дни). 1 = каждый день.
    lookback_days : int or None
        None = расширяющееся окно (все доступные данные с начала)
        число = скользящее окно фиксированной длины (последние lookback_days дней)
    verbose : bool
        Печатать прогресс

    Возвращает:
    ----------
    pd.DataFrame с колонками:
        date, y_true, y_pred, mae, pnl_loss, train_size, retrain_flag
    """
    # Сортировка по дате
    idx = np.argsort(dates)
    X = X.iloc[idx].reset_index(drop=True)
    y = y.iloc[idx].reset_index(drop=True)
    dates = dates.iloc[idx].reset_index(drop=True)

    min_train_size = train_window_days
    results = []
    last_retrain_idx = -1
    current_model = None

    for i in tqdm(range(min_train_size, len(X)), disable=not verbose, desc="Backtest"):
        # Определяем границы обучения
        if lookback_days is None:
            train_start = 0
        else:
            train_start = max(0, i - lookback_days)
        train_end = i  # обучаемся на данных до i-1 включительно, прогноз на i

        # Переобучение по расписанию
        should_retrain = (i == min_train_size) or ((i - last_retrain_idx) >= retrain_freq)

        if should_retrain:
            X_train = X.iloc[train_start:train_end]
            y_train = y.iloc[train_start:train_end]
            current_model = clone(model)
            current_model.fit(X_train, y_train)
            last_retrain_idx = i

        # Прогноз на один день
        X_test = X.iloc[i:i+1]
        y_pred = current_model.predict(X_test)[0]
        y_true = y.iloc[i]

        mae_val = mean_absolute_error([y_true], [y_pred])
        pnl_val = pnl_loss(np.array([y_true]), np.array([y_pred]))

        results.append({
            'date': dates.iloc[i],
            'y_true': y_true,
            'y_pred': y_pred,
            'mae': mae_val,
            'pnl_loss': pnl_val,
            'train_size': train_end - train_start,
            'retrain_flag': should_retrain
        })

    return pd.DataFrame(results)


def evaluate_calibration_freq(
    model,
    X,
    y,
    dates,
    train_window_days=500,
    retrain_freqs=[1, 5, 21, 63],
    lookback_days=None,
    verbose=True
):
    """Сравнивает частоты переобучения."""
    summary = []
    for freq in retrain_freqs:
        start = time.time()
        res = expanding_window_backtest(
            model=model,
            X=X,
            y=y,
            dates=dates,
            train_window_days=train_window_days,
            retrain_freq=freq,
            lookback_days=lookback_days,
            verbose=verbose
        )
        elapsed = time.time() - start
        summary.append({
            'retrain_freq': freq,
            'mean_mae': res['mae'].mean(),
            'mean_pnl_loss': res['pnl_loss'].mean(),
            'total_time_sec': elapsed,
            'num_retrains': res['retrain_flag'].sum()
        })
    return pd.DataFrame(summary)


def evaluate_lookback_window(
    model,
    X,
    y,
    dates,
    train_window_days=500,
    lookback_months=[3, 6, 12, 24],
    retrain_freq=1,
    verbose=True
):
    """Сравнивает размеры обучающего окна (скользящее окно)."""
    # Примерное число рабочих дней в месяце = 21
    lookback_days_options = [m * 21 for m in lookback_months]
    summary = []
    for ld in lookback_days_options:
        start = time.time()
        res = expanding_window_backtest(
            model=model,
            X=X,
            y=y,
            dates=dates,
            train_window_days=train_window_days,
            retrain_freq=retrain_freq,
            lookback_days=ld,
            verbose=verbose
        )
        elapsed = time.time() - start
        summary.append({
            'lookback_months': ld // 21,
            'lookback_days': ld,
            'mean_mae': res['mae'].mean(),
            'mean_pnl_loss': res['pnl_loss'].mean(),
            'total_time_sec': elapsed
        })
    return pd.DataFrame(summary)