# -*- coding: utf-8 -*-
"""tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wMTF6aXr_vXm9FwQ6LFjfCWk3Z4__ELx
"""

# src/tuning.py

import optuna
import numpy as np
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit
from sklearn.base import clone
from src.metrics import pnl_loss
from src.models import (
    SARIMAXWrapper,
    make_elasticnet_pipeline,
    make_rf_pipeline,
    make_lgb_pipeline
)

# ----------------------------------------------------------------------
# Функции предложения гиперпараметров (только чистые имена)
# ----------------------------------------------------------------------

def suggest_elasticnet_params(trial):
    return {
        'alpha': trial.suggest_float('alpha', 1e-4, 10.0, log=True),
        'l1_ratio': trial.suggest_float('l1_ratio', 0.0, 1.0),
        'use_scaler': trial.suggest_categorical('use_scaler', [True, False])
    }

def suggest_rf_params(trial):
    return {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'max_depth': trial.suggest_int('max_depth', 5, 30),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10)
        # min_samples_leaf удалён
    }

def suggest_lgb_params(trial):
    return {
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 10, 100),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True)
    }

def suggest_sarimax_params(trial):
    p = trial.suggest_int('p', 0, 3)
    d = trial.suggest_int('d', 0, 1)
    q = trial.suggest_int('q', 0, 3)
    P = trial.suggest_int('P', 0, 2)
    D = trial.suggest_int('D', 0, 1)
    Q = trial.suggest_int('Q', 0, 2)
    return {
        'order': (p, d, q),
        'seasonal_order': (P, D, Q, 5),
        'trend': trial.suggest_categorical('trend', ['c', 't', 'ct'])
    }

# ----------------------------------------------------------------------
# Построение модели (принимает чистые параметры)
# ----------------------------------------------------------------------

def build_model(model_name, params):
    if model_name == 'elasticnet':
        return make_elasticnet_pipeline(**params)
    elif model_name == 'rf':
        return make_rf_pipeline(**params)
    elif model_name == 'lgb':
        return make_lgb_pipeline(**params)
    elif model_name == 'sarimax':
        return SARIMAXWrapper(**params)
    else:
        raise ValueError(f"Unknown model: {model_name}")

# ----------------------------------------------------------------------
# Целевая функция Optuna
# ----------------------------------------------------------------------

def objective(trial, model_name, X, y, n_splits=3):
    if model_name == 'elasticnet':
        params = suggest_elasticnet_params(trial)
    elif model_name == 'rf':
        params = suggest_rf_params(trial)
    elif model_name == 'lgb':
        params = suggest_lgb_params(trial)
    elif model_name == 'sarimax':
        params = suggest_sarimax_params(trial)
    else:
        raise ValueError(f"Model {model_name} not supported")

    model = build_model(model_name, params)

    tscv = TimeSeriesSplit(n_splits=n_splits)
    losses = []
    for train_idx, val_idx in tscv.split(X):
        X_tr = X.iloc[train_idx]
        X_val = X.iloc[val_idx]
        y_tr = y.iloc[train_idx]
        y_val = y.iloc[val_idx]

        model_clone = clone(model)
        try:
            model_clone.fit(X_tr, y_tr)
            y_pred = model_clone.predict(X_val)
            loss = pnl_loss(y_val, y_pred)
            losses.append(loss)
        except Exception:
            return 1e6

    return np.mean(losses) if losses else 1e6

# ----------------------------------------------------------------------
# Основная функция настройки гиперпараметров
# ----------------------------------------------------------------------

def tune_model(model_name, X, y, n_trials=50, n_splits=3, timeout=None):
    study = optuna.create_study(
        direction='minimize',
        sampler=optuna.samplers.TPESampler(seed=42)
    )

    from functools import partial
    objective_partial = partial(
        objective,
        model_name=model_name,
        X=X,
        y=y,
        n_splits=n_splits
    )

    study.optimize(
        objective_partial,
        n_trials=n_trials,
        timeout=timeout,
        n_jobs=1,
        show_progress_bar=True
    )

    best_params = study.best_params
    best_value = study.best_value

    # Для SARIMAX преобразуем порядки в кортежи (параметры уже чистые)
    if model_name == 'sarimax':
        best_params = {
            'order': (best_params['p'], best_params['d'], best_params['q']),
            'seasonal_order': (best_params['P'], best_params['D'], best_params['Q'], 5),
            'trend': best_params['trend']
        }

    return best_params, best_value, study